package arpm_rpm_rpmhdrIndexs is
    type rpmhdrIndex is private;
    type rpmhdrIndex_access is access all rpmhdrIndex;

    type tags_type is (
        RPMTAG_HEADERSIGNATURES,
        RPMTAG_HEADERIMMUTABLE,
        RPMTAG_HEADERI18NTABLE,
        RPMSIGTAG_RSA,
        RPMSIGTAG_SHA1,
        RPMTAG_Name,
        RPMTAG_Version,
        RPMTAG_RELEASE,
        RPMTAG_Epoch,
        RPMTAG_SUMMARY,
        RPMTAG_DESCRIPTION,
        RPMTAG_BUILDTIME,
        RPMTAG_BUILDHOST,
        RPMTAG_INSTALLTIME,
        RPMTAG_SIZE,
        RPMTAG_DISTRIBUTION,
        RPMTAG_VENDOR,
        RPMTAG_GIF,
        RPMTAG_XPM,
        RPMTAG_LICENSE,
        RPMTAG_PACKAGER,
        RPMTAG_GROUP,
        RPMTAG_CHANGELOG,
        RPMTAG_SOURCE,
        RPMTAG_PATCH,
        RPMTAG_URL,
        RPMTAG_OS,
        RPMTAG_ARCH,
        RPMTAG_PREIN,
        RPMTAG_POSTIN,
        RPMTAG_PREUN,
        RPMTAG_POSTUN,
        RPMTAG_OLDFILENameS,
        RPMTAG_FILESIZES,
        RPMTAG_FILESTATES,
        RPMTAG_FILEMODES,
        RPMTAG_FILEUIDS,
        RPMTAG_FILEGIDS,
        RPMTAG_FILERDEVS,
        RPMTAG_FILEMTIMES,
        RPMTAG_FILEDIGESTS,
        RPMTAG_FILELINKTOS,
        RPMTAG_FILEFlags,
        RPMTAG_ROOT,
        RPMTAG_FILEUSERName,
        RPMTAG_FILEGROUPName,
        RPMTAG_EXCLUDE,
        RPMTAG_EXCLUSIVE,
        RPMTAG_ICON,
        RPMTAG_SOURCERPM,
        RPMTAG_FILEVERIFYFlags,
        RPMTAG_ARCHIVESIZE,
        RPMTAG_PROVIDEName,
        RPMTAG_REQUIREFlags,
        RPMTAG_REQUIREName,
        RPMTAG_REQUIREVersion,
        RPMTAG_NOSOURCE,
        RPMTAG_NOPATCH,
        RPMTAG_CONFLICTFlags,
        RPMTAG_CONFLICTName,
        RPMTAG_CONFLICTVersion,
        RPMTAG_DEFAULTPREFIX,
        RPMTAG_BUILDROOT,
        RPMTAG_INSTALLPREFIX,
        RPMTAG_EXCLUDEARCH,
        RPMTAG_EXCLUDEOS,
        RPMTAG_EXCLUSIVEARCH,
        RPMTAG_EXCLUSIVEOS,
        RPMTAG_AUTOREQPROV,
        RPMTAG_RPMVersion,
        RPMTAG_TRIGGERSCRIPTS,
        RPMTAG_TRIGGERName,
        RPMTAG_TRIGGERVersion,
        RPMTAG_TRIGGERFlags,
        RPMTAG_TRIGGERIndex,
        RPMTAG_VERIFYSCRIPT,
        RPMTAG_CHANGELOGTIME,
        RPMTAG_CHANGELOGName,
        RPMTAG_CHANGELOGTEXT,
        RPMTAG_BROKENMD5,
        RPMTAG_PREREQ,
        RPMTAG_PREINPROG,
        RPMTAG_POSTINPROG,
        RPMTAG_PREUNPROG,
        RPMTAG_POSTUNPROG,
        RPMTAG_BUILDARCHS,
        RPMTAG_OBSOLETEName,
        RPMTAG_VERIFYSCRIPTPROG,
        RPMTAG_TRIGGERSCRIPTPROG,
        RPMTAG_DOCDIR,
        RPMTAG_COOKIE,
        RPMTAG_FILEDEVICES,
        RPMTAG_FILEINODES,
        RPMTAG_FILELANGS,
        RPMTAG_PREFIXES,
        RPMTAG_INSTPREFIXES,
        RPMTAG_TRIGGERIN,
        RPMTAG_TRIGGERUN,
        RPMTAG_TRIGGERPOSTUN,
        RPMTAG_AUTOREQ,
        RPMTAG_AUTOPROV,
        RPMTAG_CAPABILITY,
        RPMTAG_SOURCEPACKAGE,
        RPMTAG_OLDORIGFILENameS,
        RPMTAG_BUILDPREREQ,
        RPMTAG_BUILDREQUIRES,
        RPMTAG_BUILDCONFLICTS,
        RPMTAG_BUILDMACROS,
        RPMTAG_PROVIDEFlags,
        RPMTAG_PROVIDEVersion,
        RPMTAG_OBSOLETEFlags,
        RPMTAG_OBSOLETEVersion,
        RPMTAG_DIRIndexES,
        RPMTAG_BASENameS,
        RPMTAG_DIRNameS,
        RPMTAG_ORIGDIRIndexES,
        RPMTAG_ORIGBASENameS,
        RPMTAG_ORIGDIRNameS,
        RPMTAG_OPTFlags,
        RPMTAG_DISTURL,
        RPMTAG_PAYLOADFormat,
        RPMTAG_PAYLOADCOMPRESSOR,
        RPMTAG_PAYLOADFlags,
        RPMTAG_INSTALLCOLOR,
        RPMTAG_INSTALLTID,
        RPMTAG_REMOVETID,
        RPMTAG_SHA1RHN,
        RPMTAG_RHNPLATFORM,
        RPMTAG_PLATFORM,
        RPMTAG_PATCHESName,
        RPMTAG_PATCHESFlags,
        RPMTAG_PATCHESVersion,
        RPMTAG_CACHECTIME,
        RPMTAG_CACHEPKGPATH,
        RPMTAG_CACHEPKGSIZE,
        RPMTAG_CACHEPKGMTIME,
        RPMTAG_FILECOLORS,
        RPMTAG_FILECLASS,
        RPMTAG_CLASSDICT,
        RPMTAG_FILEDEPENDSX,
        RPMTAG_FILEDEPENDSN,
        RPMTAG_DEPENDSDICT,
        RPMTAG_SOURCEPKGID,
        RPMTAG_FILECONTEXTS,
        RPMTAG_FSCONTEXTS,
        RPMTAG_RECONTEXTS,
        RPMTAG_POLICIES,
        RPMTAG_PRETRANS,
        RPMTAG_POSTTRANS,
        RPMTAG_PRETRANSPROG,
        RPMTAG_POSTTRANSPROG,
        RPMTAG_DISTTAG,
        RPMTAG_SUGGESTSName,
        RPMTAG_SUGGESTSVersion,
        RPMTAG_SUGGESTSFlags,
        RPMTAG_ENHANCESName,
        RPMTAG_ENHANCESVersion,
        RPMTAG_ENHANCESFlags,
        RPMTAG_PRIORITY,
        RPMTAG_CVSID,
        RPMTAG_BLINKPKGID,
        RPMTAG_BLINKHDRID,
        RPMTAG_BLINKNEVRA,
        RPMTAG_FLINKPKGID,
        RPMTAG_FLINKHDRID,
        RPMTAG_FLINKNEVRA,
        RPMTAG_PACKAGEORIGIN,
        RPMTAG_TRIGGERPREIN,
        RPMTAG_BUILDSUGGESTS,
        RPMTAG_BUILDENHANCES,
        RPMTAG_SCRIPTSTATES,
        RPMTAG_SCRIPTMETRICS,
        RPMTAG_BUILDCPUCLOCK,
        RPMTAG_FILEDIGESTALGOS,
        RPMTAG_VARIANTS,
        RPMTAG_XMAJOR,
        RPMTAG_XMINOR,
        RPMTAG_REPOTAG,
        RPMTAG_KEYWORDS,
        RPMTAG_BUILDPLATFORMS,
        RPMTAG_PACKAGECOLOR,
        RPMTAG_PACKAGEPREFCOLOR,
        RPMTAG_XATTRSDICT,
        RPMTAG_FILEXATTRSX,
        RPMTAG_DEPATTRSDICT,
        RPMTAG_CONFLICTATTRSX,
        RPMTAG_OBSOLETEATTRSX,
        RPMTAG_PROVIDEATTRSX,
        RPMTAG_REQUIREATTRSX,
        RPMTAG_BUILDProvides,
        RPMTAG_BUILDOBSOLETES,
        RPMTAG_DBINSTANCE,
        RPMTAG_NVRA,
        RPMTAG_FILENameS,
        RPMTAG_FILEPROVIDE,
        RPMTAG_FILEREQUIRE,
        RPMTAG_FSNameS,
        RPMTAG_FSSIZES,
        RPMTAG_TRIGGERCONDS,
        RPMTAG_TRIGGERTYPE,
        RPMTAG_ORIGFILENameS,
        RPMTAG_LONGFILESIZES,
        RPMTAG_LONGSIZE,
        RPMTAG_FILECAPS,
        RPMTAG_FILEDIGESTALGO,
        RPMTAG_BUGURL,
        RPMTAG_EVR,
        RPMTAG_NVR,
        RPMTAG_NEVR,
        RPMTAG_NEVRA,
        RPMTAG_HEADERCOLOR,
        RPMTAG_VERBOSE,
        RPMTAG_EpochNUM,
        RPMTAG_PREINFlags,
        RPMTAG_POSTINFlags,
        RPMTAG_PREUNFlags,
        RPMTAG_POSTUNFlags,
        RPMTAG_PRETRANSFlags,
        RPMTAG_POSTTRANSFlags,
        RPMTAG_VERIFYSCRIPTFlags,
        RPMTAG_TRIGGERSCRIPTFlags,
        RPMTAG_COLLECTIONS,
        RPMTAG_POLICYNameS,
        RPMTAG_POLICYTYPES,
        RPMTAG_POLICYTYPESIndexES,
        RPMTAG_POLICYFlags,
        RPMTAG_VCS,
        RPMTAG_ORDERName,
        RPMTAG_ORDERVersion,
        RPMTAG_ORDERFlags,
        RPMTAG_MSSFMANIFEST,
        RPMTAG_MSSFDOMAIN,
        RPMTAG_INSTFILENameS,
        RPMTAG_REQUIRENEVRS,
        RPMTAG_PROVIDENEVRS,
        RPMTAG_OBSOLETENEVRS,
        RPMTAG_CONFLICTNEVRS,
        RPMTAG_FILENLINKS
        );
    for tags_type use (
        RPMTAG_HEADERSIGNATURES => 62,
        RPMTAG_HEADERIMMUTABLE => 63,
        RPMTAG_HEADERI18NTABLE => 100,
        RPMSIGTAG_RSA => 268,
        RPMSIGTAG_SHA1 => 269,
        -- TODO
        -- The values are different for the SIGNATURE and PAYLOAD sections
        RPMTAG_Name                 => 1000,
        RPMTAG_Version              => 1001,
        RPMTAG_RELEASE              => 1002,
        RPMTAG_Epoch                => 1003,
        RPMTAG_SUMMARY              => 1004,
        RPMTAG_DESCRIPTION          => 1005,
        RPMTAG_BUILDTIME            => 1006,
        RPMTAG_BUILDHOST            => 1007,
        RPMTAG_INSTALLTIME          => 1008,
        RPMTAG_SIZE                 => 1009,
        RPMTAG_DISTRIBUTION         => 1010,
        RPMTAG_VENDOR               => 1011,
        RPMTAG_GIF                  => 1012,
        RPMTAG_XPM                  => 1013,
        RPMTAG_LICENSE              => 1014,
        RPMTAG_PACKAGER             => 1015,
        RPMTAG_GROUP                => 1016,
        RPMTAG_CHANGELOG            => 1017,
        RPMTAG_SOURCE               => 1018,
        RPMTAG_PATCH                => 1019,
        RPMTAG_URL                  => 1020,
        RPMTAG_OS                   => 1021,
        RPMTAG_ARCH                 => 1022,
        RPMTAG_PREIN                => 1023,
        RPMTAG_POSTIN               => 1024,
        RPMTAG_PREUN                => 1025,
        RPMTAG_POSTUN               => 1026,
        RPMTAG_OLDFILENameS         => 1027,
        RPMTAG_FILESIZES            => 1028,
        RPMTAG_FILESTATES           => 1029,
        RPMTAG_FILEMODES            => 1030,
        RPMTAG_FILEUIDS             => 1031,
        RPMTAG_FILEGIDS             => 1032,
        RPMTAG_FILERDEVS            => 1033,
        RPMTAG_FILEMTIMES           => 1034,
        RPMTAG_FILEDIGESTS          => 1035,
        RPMTAG_FILELINKTOS          => 1036,
        RPMTAG_FILEFlags            => 1037,
        RPMTAG_ROOT                 => 1038,
        RPMTAG_FILEUSERName         => 1039,
        RPMTAG_FILEGROUPName        => 1040,
        RPMTAG_EXCLUDE              => 1041,
        RPMTAG_EXCLUSIVE            => 1042,
        RPMTAG_ICON                 => 1043,
        RPMTAG_SOURCERPM            => 1044,
        RPMTAG_FILEVERIFYFlags      => 1045,
        RPMTAG_ARCHIVESIZE          => 1046,
        RPMTAG_PROVIDEName          => 1047,
        RPMTAG_REQUIREFlags         => 1048,
        RPMTAG_REQUIREName          => 1049,
        RPMTAG_REQUIREVersion       => 1050,
        RPMTAG_NOSOURCE             => 1051,
        RPMTAG_NOPATCH              => 1052,
        RPMTAG_CONFLICTFlags        => 1053,
        RPMTAG_CONFLICTName         => 1054,
        RPMTAG_CONFLICTVersion      => 1055,
        RPMTAG_DEFAULTPREFIX        => 1056,
        RPMTAG_BUILDROOT            => 1057,
        RPMTAG_INSTALLPREFIX        => 1058,
        RPMTAG_EXCLUDEARCH          => 1059,
        RPMTAG_EXCLUDEOS            => 1060,
        RPMTAG_EXCLUSIVEARCH        => 1061,
        RPMTAG_EXCLUSIVEOS          => 1062,
        RPMTAG_AUTOREQPROV          => 1063,
        RPMTAG_RPMVersion           => 1064,
        RPMTAG_TRIGGERSCRIPTS       => 1065,
        RPMTAG_TRIGGERName          => 1066,
        RPMTAG_TRIGGERVersion       => 1067,
        RPMTAG_TRIGGERFlags         => 1068,
        RPMTAG_TRIGGERIndex         => 1069,
        RPMTAG_VERIFYSCRIPT         => 1079,
        RPMTAG_CHANGELOGTIME        => 1080,
        RPMTAG_CHANGELOGName        => 1081,
        RPMTAG_CHANGELOGTEXT        => 1082,
        RPMTAG_BROKENMD5            => 1083,
        RPMTAG_PREREQ               => 1084,
        RPMTAG_PREINPROG            => 1085,
        RPMTAG_POSTINPROG           => 1086,
        RPMTAG_PREUNPROG            => 1087,
        RPMTAG_POSTUNPROG           => 1088,
        RPMTAG_BUILDARCHS           => 1089,
        RPMTAG_OBSOLETEName         => 1090,
        RPMTAG_VERIFYSCRIPTPROG     => 1091,
        RPMTAG_TRIGGERSCRIPTPROG    => 1092,
        RPMTAG_DOCDIR               => 1093,
        RPMTAG_COOKIE               => 1094,
        RPMTAG_FILEDEVICES          => 1095,
        RPMTAG_FILEINODES           => 1096,
        RPMTAG_FILELANGS            => 1097,
        RPMTAG_PREFIXES             => 1098,
        RPMTAG_INSTPREFIXES         => 1099,
        RPMTAG_TRIGGERIN            => 1100,
        RPMTAG_TRIGGERUN            => 1101,
        RPMTAG_TRIGGERPOSTUN        => 1102,
        RPMTAG_AUTOREQ              => 1103,
        RPMTAG_AUTOPROV             => 1104,
        RPMTAG_CAPABILITY           => 1105,
        RPMTAG_SOURCEPACKAGE        => 1106,
        RPMTAG_OLDORIGFILENameS     => 1107,
        RPMTAG_BUILDPREREQ          => 1108,
        RPMTAG_BUILDREQUIRES        => 1109,
        RPMTAG_BUILDCONFLICTS       => 1110,
        RPMTAG_BUILDMACROS          => 1111,
        RPMTAG_PROVIDEFlags         => 1112,
        RPMTAG_PROVIDEVersion       => 1113,
        RPMTAG_OBSOLETEFlags        => 1114,
        RPMTAG_OBSOLETEVersion      => 1115,
        RPMTAG_DIRIndexES           => 1116,
        RPMTAG_BASENameS            => 1117,
        RPMTAG_DIRNameS             => 1118,
        RPMTAG_ORIGDIRIndexES       => 1119,
        RPMTAG_ORIGBASENameS        => 1120,
        RPMTAG_ORIGDIRNameS         => 1121,
        RPMTAG_OPTFlags             => 1122,
        RPMTAG_DISTURL              => 1123,
        RPMTAG_PAYLOADFormat        => 1124,
        RPMTAG_PAYLOADCOMPRESSOR    => 1125,
        RPMTAG_PAYLOADFlags         => 1126,
        RPMTAG_INSTALLCOLOR         => 1127,
        RPMTAG_INSTALLTID           => 1128,
        RPMTAG_REMOVETID            => 1129,
        RPMTAG_SHA1RHN              => 1130,
        RPMTAG_RHNPLATFORM          => 1131,
        RPMTAG_PLATFORM             => 1132,
        RPMTAG_PATCHESName          => 1133,
        RPMTAG_PATCHESFlags         => 1134,
        RPMTAG_PATCHESVersion       => 1135,
        RPMTAG_CACHECTIME           => 1136,
        RPMTAG_CACHEPKGPATH         => 1137,
        RPMTAG_CACHEPKGSIZE         => 1138,
        RPMTAG_CACHEPKGMTIME        => 1139,
        RPMTAG_FILECOLORS           => 1140,
        RPMTAG_FILECLASS            => 1141,
        RPMTAG_CLASSDICT            => 1142,
        RPMTAG_FILEDEPENDSX         => 1143,
        RPMTAG_FILEDEPENDSN         => 1144,
        RPMTAG_DEPENDSDICT          => 1145,
        RPMTAG_SOURCEPKGID          => 1146,
        RPMTAG_FILECONTEXTS         => 1147,
        RPMTAG_FSCONTEXTS           => 1148,
        RPMTAG_RECONTEXTS           => 1149,
        RPMTAG_POLICIES             => 1150,
        RPMTAG_PRETRANS             => 1151,
        RPMTAG_POSTTRANS            => 1152,
        RPMTAG_PRETRANSPROG         => 1153,
        RPMTAG_POSTTRANSPROG        => 1154,
        RPMTAG_DISTTAG              => 1155,
        RPMTAG_SUGGESTSName         => 1156,
        RPMTAG_SUGGESTSVersion      => 1157,
        RPMTAG_SUGGESTSFlags        => 1158,
        RPMTAG_ENHANCESName         => 1159,
        RPMTAG_ENHANCESVersion      => 1160,
        RPMTAG_ENHANCESFlags        => 1161,
        RPMTAG_PRIORITY             => 1162,
        RPMTAG_CVSID                => 1163,
        RPMTAG_BLINKPKGID           => 1164,
        RPMTAG_BLINKHDRID           => 1165,
        RPMTAG_BLINKNEVRA           => 1166,
        RPMTAG_FLINKPKGID           => 1167,
        RPMTAG_FLINKHDRID           => 1168,
        RPMTAG_FLINKNEVRA           => 1169,
        RPMTAG_PACKAGEORIGIN        => 1170,
        RPMTAG_TRIGGERPREIN         => 1171,
        RPMTAG_BUILDSUGGESTS        => 1172,
        RPMTAG_BUILDENHANCES        => 1173,
        RPMTAG_SCRIPTSTATES         => 1174,
        RPMTAG_SCRIPTMETRICS        => 1175,
        RPMTAG_BUILDCPUCLOCK        => 1176,
        RPMTAG_FILEDIGESTALGOS      => 1177,
        RPMTAG_VARIANTS             => 1178,
        RPMTAG_XMAJOR               => 1179,
        RPMTAG_XMINOR               => 1180,
        RPMTAG_REPOTAG              => 1181,
        RPMTAG_KEYWORDS             => 1182,
        RPMTAG_BUILDPLATFORMS       => 1183,
        RPMTAG_PACKAGECOLOR         => 1184,
        RPMTAG_PACKAGEPREFCOLOR     => 1185,
        RPMTAG_XATTRSDICT           => 1186,
        RPMTAG_FILEXATTRSX          => 1187,
        RPMTAG_DEPATTRSDICT         => 1188,
        RPMTAG_CONFLICTATTRSX       => 1189,
        RPMTAG_OBSOLETEATTRSX       => 1190,
        RPMTAG_PROVIDEATTRSX        => 1191,
        RPMTAG_REQUIREATTRSX        => 1192,
        RPMTAG_BUILDProvides        => 1193,
        RPMTAG_BUILDOBSOLETES       => 1194,
        RPMTAG_DBINSTANCE           => 1195,
        RPMTAG_NVRA                 => 1196,
        RPMTAG_FILENameS            => 5000,
        RPMTAG_FILEPROVIDE          => 5001,
        RPMTAG_FILEREQUIRE          => 5002,
        RPMTAG_FSNameS              => 5003,
        RPMTAG_FSSIZES              => 5004,
        RPMTAG_TRIGGERCONDS         => 5005,
        RPMTAG_TRIGGERTYPE          => 5006,
        RPMTAG_ORIGFILENameS        => 5007,
        RPMTAG_LONGFILESIZES        => 5008,
        RPMTAG_LONGSIZE             => 5009,
        RPMTAG_FILECAPS             => 5010,
        RPMTAG_FILEDIGESTALGO       => 5011,
        RPMTAG_BUGURL               => 5012,
        RPMTAG_EVR                  => 5013,
        RPMTAG_NVR                  => 5014,
        RPMTAG_NEVR                 => 5015,
        RPMTAG_NEVRA                => 5016,
        RPMTAG_HEADERCOLOR          => 5017,
        RPMTAG_VERBOSE              => 5018,
        RPMTAG_EpochNUM             => 5019,
        RPMTAG_PREINFlags           => 5020,
        RPMTAG_POSTINFlags          => 5021,
        RPMTAG_PREUNFlags           => 5022,
        RPMTAG_POSTUNFlags          => 5023,
        RPMTAG_PRETRANSFlags        => 5024,
        RPMTAG_POSTTRANSFlags       => 5025,
        RPMTAG_VERIFYSCRIPTFlags    => 5026,
        RPMTAG_TRIGGERSCRIPTFlags   => 5027,
        RPMTAG_COLLECTIONS          => 5029,
        RPMTAG_POLICYNameS          => 5030,
        RPMTAG_POLICYTYPES          => 5031,
        RPMTAG_POLICYTYPESIndexES   => 5032,
        RPMTAG_POLICYFlags          => 5033,
        RPMTAG_VCS                  => 5034,
        RPMTAG_ORDERName            => 5035,
        RPMTAG_ORDERVersion         => 5036,
        RPMTAG_ORDERFlags           => 5037,
        RPMTAG_MSSFMANIFEST         => 5038,
        RPMTAG_MSSFDOMAIN           => 5039,
        RPMTAG_INSTFILENameS        => 5040,
        RPMTAG_REQUIRENEVRS         => 5041,
        RPMTAG_PROVIDENEVRS         => 5042,
        RPMTAG_OBSOLETENEVRS        => 5043,
        RPMTAG_CONFLICTNEVRS        => 5044,
        RPMTAG_FILENLINKS           => 5045
        );

    type Format_type is
        (RPM_NULL_TYPE,
        RPM_CHAR_TYPE,
        RPM_int8_TYPE,
        RPM_int16_TYPE,
        RPM_int32_TYPE,
        RPM_int64_TYPE,
        RPM_STRING_TYPE,
        RPM_BIN_TYPE,
        RPM_STRING_ARRAY_TYPE,
        RPM_I18NSTRING_TYPE);
    for Format_type use
        (RPM_NULL_TYPE => 0,
        RPM_CHAR_TYPE => 1,
        RPM_int8_TYPE => 2,
        RPM_int16_TYPE => 3,
        RPM_int32_TYPE => 4,
        RPM_int64_TYPE => 5,
        RPM_STRING_TYPE => 6,
        RPM_BIN_TYPE => 7,
        RPM_STRING_ARRAY_TYPE => 8 ,
        RPM_I18NSTRING_TYPE =>9
        );
    function Format(Index : in rpmhdrIndex) return Format_type;
    function Tag(Index : in rpmhdrIndex) return tags_type;
    function Data_Items( Index : in rpmhdrIndex) return Integer;
    function Data_Offset ( Index : in rpmhdrIndex) return Integer;
    type four_byte_number is range 0..2**(4*8)-1;
    for four_byte_number'Size use 32;
    type two_byte_number is range 0..2**(2*8)-1;
    for two_byte_number'Size use 16;
    private
    type rpmhdrIndex is record
        tag : four_byte_number := 0;
        Format : four_byte_number := 0;
        Data_Offset :  four_byte_number := 0;
        number_of_data_items  : four_byte_number := 0;
    end record;
    for rpmhdrIndex'Size use 16*8;


end arpm_rpm_rpmhdrIndexs;

