with Interfaces.C; use Interfaces.C;
with Ada.Strings. Unbounded; use Ada.Strings.Unbounded;
with Ada.Unchecked_Deallocation;
with Interfaces.C.Pointers;
with Interfaces.C.Strings; use Interfaces.C.Strings;
with Ada.Containers.Vectors;
with Ada.Containers.Ordered_Sets;
package ARPM_RPM_Types is
   package ARPM_Vector_Container_Package is new Ada.Containers.Vectors(
     Element_Type => Unbounded_String, Index_Type => Positive
     );
   subtype ARPM_Vector_Container is ARPM_Vector_Container_Package.Vector;

   type SHA256S is array (1..64) of Character;
   package ARPM_Map_Container_Package is new Ada.Containers.Ordered_Sets(
     Element_Type => SHA256S);
   subtype Arpm_Osets_Container is ARPM_Map_Container_Package.Set;
   type Tags_Type is (
     RPMTag_HeaderSIGNATURES,
     RPMTag_HeaderIMMUTABLE,
     RPMTag_HeaderI18NTABLE,
     RPMSIGTag_RSA,
     RPMSIGTag_SHA1,
     RPMTag_Name,
     RPMTag_Version,
     RPMTag_RELEASE,
     RPMTag_Epoch,
     RPMTag_SUMMARY,
     RPMTag_DESCRIPTION,
     RPMTag_BUILDTIME,
     RPMTag_BUILDHOST,
     RPMTag_INSTALLTIME,
     RPMTag_SIZE,
     RPMTag_DISTRIBUTION,
     RPMTag_VENDOR,
     RPMTag_GIF,
     RPMTag_XPM,
     RPMTag_License,
     RPMTag_PACKAGER,
     RPMTag_GROUP,
     RPMTag_CHANGELOG,
     RPMTag_SOURCE,
     RPMTag_PATCH,
     RPMTag_URL,
     RPMTag_OS,
     RPMTag_ARCH,
     RPMTag_PREIN,
     RPMTag_POSTIN,
     RPMTag_PREUN,
     RPMTag_POSTUN,
     RPMTag_OLDFILENameS,
     RPMTag_FilesIZES,
     RPMTag_FilesTATES,
     RPMTag_FILEMODES,
     RPMTag_FILEUIDS,
     RPMTag_FILEGIDS,
     RPMTag_FILERDEVS,
     RPMTag_FILEMTIMES,
     RPMTag_FILEDIGESTS,
     RPMTag_FILELINKTOS,
     RPMTag_FILEFlags,
     RPMTag_ROOT,
     RPMTag_FILEUSERName,
     RPMTag_FILEGROUPName,
     RPMTag_EXCLUDE,
     RPMTag_EXCLUSIVE,
     RPMTag_ICON,
     RPMTag_SOURCERPM,
     RPMTag_FILEVERIFYFlags,
     RPMTag_ARCHIVESIZE,
     RPMTag_PROVIDEName,
     RPMTag_REQUIREFlags,
     RPMTag_REQUIREName,
     RPMTag_REQUIREVersion,
     RPMTag_NOSOURCE,
     RPMTag_NOPATCH,
     RPMTag_CONFLICTFlags,
     RPMTag_CONFLICTName,
     RPMTag_CONFLICTVersion,
     RPMTag_DEFAULTPREFIX,
     RPMTag_BUILDROOT,
     RPMTag_INSTALLPREFIX,
     RPMTag_EXCLUDEARCH,
     RPMTag_EXCLUDEOS,
     RPMTag_EXCLUSIVEARCH,
     RPMTag_EXCLUSIVEOS,
     RPMTag_AUTOREQPROV,
     RPMTag_RPMVersion,
     RPMTag_TRIGGERSCRIPTS,
     RPMTag_TRIGGERName,
     RPMTag_TRIGGERVersion,
     RPMTag_TRIGGERFlags,
     RPMTag_TRIGGERIndex,
     RPMTag_VERIFYSCRIPT,
     RPMTag_CHANGELOGTIME,
     RPMTag_CHANGELOGName,
     RPMTag_CHANGELOGTEXT,
     RPMTag_BROKENMD5,
     RPMTag_PREREQ,
     RPMTag_PREINPROG,
     RPMTag_POSTINPROG,
     RPMTag_PREUNPROG,
     RPMTag_POSTUNPROG,
     RPMTag_BUILDARCHS,
     RPMTag_OBSOLETEName,
     RPMTag_VERIFYSCRIPTPROG,
     RPMTag_TRIGGERSCRIPTPROG,
     RPMTag_DOCDIR,
     RPMTag_COOKIE,
     RPMTag_FILEDEVICES,
     RPMTag_FILEINODES,
     RPMTag_FILELANGS,
     RPMTag_PREFIXES,
     RPMTag_INSTPREFIXES,
     RPMTag_TRIGGERIN,
     RPMTag_TRIGGERUN,
     RPMTag_TRIGGERPOSTUN,
     RPMTag_AUTOREQ,
     RPMTag_AUTOPROV,
     RPMTag_CAPABILITY,
     RPMTag_SOURCEPACKAGE,
     RPMTag_OLDORIGFILENameS,
     RPMTag_BUILDPREREQ,
     RPMTag_BUILDREQUIRES,
     RPMTag_BUILDCONFLICTS,
     RPMTag_BUILDMACROS,
     RPMTag_PROVIDEFlags,
     RPMTag_PROVIDEVersion,
     RPMTag_OBSOLETEFlags,
     RPMTag_OBSOLETEVersion,
     RPMTag_DIRIndexES,
     RPMTag_BASENameS,
     RPMTag_DIRNameS,
     RPMTag_ORIGDIRIndexES,
     RPMTag_ORIGBASENameS,
     RPMTag_ORIGDIRNameS,
     RPMTag_OPTFLAGS,
     RPMTag_DISTURL,
     RPMTag_PAYLOADFormat,
     RPMTag_PAYLOADCOMPRESSOR,
     RPMTag_PAYLOADFlags,
     RPMTag_INSTALLCOLOR,
     RPMTag_INSTALLTID,
     RPMTag_REMOVETID,
     RPMTag_SHA1RHN,
     RPMTag_RHNPLATFORM,
     RPMTag_PLATFORM,
     RPMTag_PATCHESName,
     RPMTag_PATCHESFlags,
     RPMTag_PATCHESVersion,
     RPMTag_CACHECTIME,
     RPMTag_CACHEPKGPATH,
     RPMTag_CACHEPKGSIZE,
     RPMTag_CACHEPKGMTIME,
     RPMTag_FILECOLORS,
     RPMTag_FILECLASS,
     RPMTag_CLASSDICT,
     RPMTag_FILEDEPENDSX,
     RPMTag_FILEDEPENDSN,
     RPMTag_DEPENDSDICT,
     RPMTag_SOURCEPKGID,
     RPMTag_FILECONTEXTS,
     RPMTag_FSCONTEXTS,
     RPMTag_RECONTEXTS,
     RPMTag_POLICIES,
     RPMTag_PRETRANS,
     RPMTag_POSTTRANS,
     RPMTag_PRETRANSPROG,
     RPMTag_POSTTRANSPROG,
     RPMTag_DISTTag,
     RPMTag_SUGGESTSName,
     RPMTag_SUGGESTSVersion,
     RPMTag_SUGGESTSFlags,
     RPMTag_ENHANCESName,
     RPMTag_ENHANCESVersion,
     RPMTag_ENHANCESFlags,
     RPMTag_PRIORITY,
     RPMTag_CVSID,
     RPMTag_BLINKPKGID,
     RPMTag_BLINKHDRID,
     RPMTag_BLINKNEVRA,
     RPMTag_FLINKPKGID,
     RPMTag_FLINKHDRID,
     RPMTag_FLINKNEVRA,
     RPMTag_PACKAGEORIGIN,
     RPMTag_TRIGGERPREIN,
     RPMTag_BUILDSUGGESTS,
     RPMTag_BUILDENHANCES,
     RPMTag_SCRIPTSTATES,
     RPMTag_SCRIPTMETRICS,
     RPMTag_BUILDCPUCLOCK,
     RPMTag_FILEDIGESTALGOS,
     RPMTag_VARIANTS,
     RPMTag_XMAJOR,
     RPMTag_XMINOR,
     RPMTag_REPOTag,
     RPMTag_KEYWORDS,
     RPMTag_BUILDPLATFORMS,
     RPMTag_PACKAGECOLOR,
     RPMTag_PACKAGEPREFCOLOR,
     RPMTag_XATTRSDICT,
     RPMTag_FILEXATTRSX,
     RPMTag_DEPATTRSDICT,
     RPMTag_CONFLICTATTRSX,
     RPMTag_OBSOLETEATTRSX,
     RPMTag_PROVIDEATTRSX,
     RPMTag_REQUIREATTRSX,
     RPMTag_BUILDProvides,
     RPMTag_BUILDOBSOLETES,
     RPMTag_DBINSTANCE,
     RPMTag_NVRA,
     RPMTag_FILENameS,
     RPMTag_FILEPROVIDE,
     RPMTag_FILEREQUIRE,
     RPMTag_FSNameS,
     RPMTag_FSSIZES,
     RPMTag_TRIGGERCONDS,
     RPMTag_TRIGGERTYPE,
     RPMTag_ORIGFILENameS,
     RPMTag_LONGFilesIZES,
     RPMTag_LONGSIZE,
     RPMTag_FILECAPS,
     RPMTag_FILEDIGESTALGO,
     RPMTag_BUGURL,
     RPMTag_EVR,
     RPMTag_NVR,
     RPMTag_NEVR,
     RPMTag_NEVRA,
     RPMTag_HeaderCOLOR,
     RPMTag_VERBOSE,
     RPMTag_EpochNUM,
     RPMTag_PREINFlags,
     RPMTag_POSTINFlags,
     RPMTag_PREUNFlags,
     RPMTag_POSTUNFlags,
     RPMTag_PRETRANSFlags,
     RPMTag_POSTTRANSFlags,
     RPMTag_VERIFYSCRIPTFlags,
     RPMTag_TRIGGERSCRIPTFlags,
     RPMTag_COLLECTIONS,
     RPMTag_POLICYNameS,
     RPMTag_POLICYTYPES,
     RPMTag_POLICYTYPESIndexES,
     RPMTag_POLICYFlags,
     RPMTag_VCS,
     RPMTag_ORDERName,
     RPMTag_ORDERVersion,
     RPMTag_ORDERFlags,
     RPMTag_MSSFMANIFEST,
     RPMTag_MSSFDOMAIN,
     RPMTag_INSTFILENameS,
     RPMTag_REQUIRENEVRS,
     RPMTag_PROVIDENEVRS,
     RPMTag_OBSOLETENEVRS,
     RPMTag_CONFLICTNEVRS,
     RPMTag_FILENLINKS
     );
   for Tags_Type use (
     RPMTag_HeaderSIGNATURES => 62,
     RPMTag_HeaderIMMUTABLE => 63,
     RPMTag_HeaderI18NTABLE => 100,
     RPMSIGTag_RSA => 268,
     RPMSIGTag_SHA1 => 269,
     -- TODO
     -- The values are different for the SIGNATURE and PAYLOAD sections
     RPMTag_Name          => 1000,
     RPMTag_Version         => 1001,
     RPMTag_RELEASE         => 1002,
     RPMTag_Epoch         => 1003,
     RPMTag_SUMMARY         => 1004,
     RPMTag_DESCRIPTION      => 1005,
     RPMTag_BUILDTIME       => 1006,
     RPMTag_BUILDHOST       => 1007,
     RPMTag_INSTALLTIME      => 1008,
     RPMTag_SIZE          => 1009,
     RPMTag_DISTRIBUTION      => 1010,
     RPMTag_VENDOR         => 1011,
     RPMTag_GIF           => 1012,
     RPMTag_XPM           => 1013,
     RPMTag_License         => 1014,
     RPMTag_PACKAGER        => 1015,
     RPMTag_GROUP         => 1016,
     RPMTag_CHANGELOG       => 1017,
     RPMTag_SOURCE         => 1018,
     RPMTag_PATCH         => 1019,
     RPMTag_URL           => 1020,
     RPMTag_OS            => 1021,
     RPMTag_ARCH          => 1022,
     RPMTag_PREIN         => 1023,
     RPMTag_POSTIN         => 1024,
     RPMTag_PREUN         => 1025,
     RPMTag_POSTUN         => 1026,
     RPMTag_OLDFILENameS      => 1027,
     RPMTag_FilesIZES       => 1028,
     RPMTag_FilesTATES       => 1029,
     RPMTag_FILEMODES       => 1030,
     RPMTag_FILEUIDS        => 1031,
     RPMTag_FILEGIDS        => 1032,
     RPMTag_FILERDEVS       => 1033,
     RPMTag_FILEMTIMES       => 1034,
     RPMTag_FILEDIGESTS      => 1035,
     RPMTag_FILELINKTOS      => 1036,
     RPMTag_FILEFlags       => 1037,
     RPMTag_ROOT          => 1038,
     RPMTag_FILEUSERName      => 1039,
     RPMTag_FILEGROUPName     => 1040,
     RPMTag_EXCLUDE         => 1041,
     RPMTag_EXCLUSIVE       => 1042,
     RPMTag_ICON          => 1043,
     RPMTag_SOURCERPM       => 1044,
     RPMTag_FILEVERIFYFlags    => 1045,
     RPMTag_ARCHIVESIZE      => 1046,
     RPMTag_PROVIDEName      => 1047,
     RPMTag_REQUIREFlags      => 1048,
     RPMTag_REQUIREName      => 1049,
     RPMTag_REQUIREVersion     => 1050,
     RPMTag_NOSOURCE        => 1051,
     RPMTag_NOPATCH         => 1052,
     RPMTag_CONFLICTFlags     => 1053,
     RPMTag_CONFLICTName      => 1054,
     RPMTag_CONFLICTVersion    => 1055,
     RPMTag_DEFAULTPREFIX     => 1056,
     RPMTag_BUILDROOT       => 1057,
     RPMTag_INSTALLPREFIX     => 1058,
     RPMTag_EXCLUDEARCH      => 1059,
     RPMTag_EXCLUDEOS       => 1060,
     RPMTag_EXCLUSIVEARCH     => 1061,
     RPMTag_EXCLUSIVEOS      => 1062,
     RPMTag_AUTOREQPROV      => 1063,
     RPMTag_RPMVersion       => 1064,
     RPMTag_TRIGGERSCRIPTS     => 1065,
     RPMTag_TRIGGERName      => 1066,
     RPMTag_TRIGGERVersion     => 1067,
     RPMTag_TRIGGERFlags      => 1068,
     RPMTag_TRIGGERIndex      => 1069,
     RPMTag_VERIFYSCRIPT      => 1079,
     RPMTag_CHANGELOGTIME     => 1080,
     RPMTag_CHANGELOGName     => 1081,
     RPMTag_CHANGELOGTEXT     => 1082,
     RPMTag_BROKENMD5       => 1083,
     RPMTag_PREREQ         => 1084,
     RPMTag_PREINPROG       => 1085,
     RPMTag_POSTINPROG       => 1086,
     RPMTag_PREUNPROG       => 1087,
     RPMTag_POSTUNPROG       => 1088,
     RPMTag_BUILDARCHS       => 1089,
     RPMTag_OBSOLETEName      => 1090,
     RPMTag_VERIFYSCRIPTPROG   => 1091,
     RPMTag_TRIGGERSCRIPTPROG   => 1092,
     RPMTag_DOCDIR         => 1093,
     RPMTag_COOKIE         => 1094,
     RPMTag_FILEDEVICES      => 1095,
     RPMTag_FILEINODES       => 1096,
     RPMTag_FILELANGS       => 1097,
     RPMTag_PREFIXES        => 1098,
     RPMTag_INSTPREFIXES      => 1099,
     RPMTag_TRIGGERIN       => 1100,
     RPMTag_TRIGGERUN       => 1101,
     RPMTag_TRIGGERPOSTUN     => 1102,
     RPMTag_AUTOREQ         => 1103,
     RPMTag_AUTOPROV        => 1104,
     RPMTag_CAPABILITY       => 1105,
     RPMTag_SOURCEPACKAGE     => 1106,
     RPMTag_OLDORIGFILENameS   => 1107,
     RPMTag_BUILDPREREQ      => 1108,
     RPMTag_BUILDREQUIRES     => 1109,
     RPMTag_BUILDCONFLICTS     => 1110,
     RPMTag_BUILDMACROS      => 1111,
     RPMTag_PROVIDEFlags      => 1112,
     RPMTag_PROVIDEVersion     => 1113,
     RPMTag_OBSOLETEFlags     => 1114,
     RPMTag_OBSOLETEVersion    => 1115,
     RPMTag_DIRIndexES       => 1116,
     RPMTag_BASENameS       => 1117,
     RPMTag_DIRNameS        => 1118,
     RPMTag_ORIGDIRIndexES     => 1119,
     RPMTag_ORIGBASENameS     => 1120,
     RPMTag_ORIGDIRNameS      => 1121,
     RPMTag_OPTFLAGS        => 1122,
     RPMTag_DISTURL         => 1123,
     RPMTag_PAYLOADFormat     => 1124,
     RPMTag_PAYLOADCOMPRESSOR   => 1125,
     RPMTag_PAYLOADFlags      => 1126,
     RPMTag_INSTALLCOLOR      => 1127,
     RPMTag_INSTALLTID       => 1128,
     RPMTag_REMOVETID       => 1129,
     RPMTag_SHA1RHN         => 1130,
     RPMTag_RHNPLATFORM      => 1131,
     RPMTag_PLATFORM        => 1132,
     RPMTag_PATCHESName      => 1133,
     RPMTag_PATCHESFlags      => 1134,
     RPMTag_PATCHESVersion     => 1135,
     RPMTag_CACHECTIME       => 1136,
     RPMTag_CACHEPKGPATH      => 1137,
     RPMTag_CACHEPKGSIZE      => 1138,
     RPMTag_CACHEPKGMTIME     => 1139,
     RPMTag_FILECOLORS       => 1140,
     RPMTag_FILECLASS       => 1141,
     RPMTag_CLASSDICT       => 1142,
     RPMTag_FILEDEPENDSX      => 1143,
     RPMTag_FILEDEPENDSN      => 1144,
     RPMTag_DEPENDSDICT      => 1145,
     RPMTag_SOURCEPKGID      => 1146,
     RPMTag_FILECONTEXTS      => 1147,
     RPMTag_FSCONTEXTS       => 1148,
     RPMTag_RECONTEXTS       => 1149,
     RPMTag_POLICIES        => 1150,
     RPMTag_PRETRANS        => 1151,
     RPMTag_POSTTRANS       => 1152,
     RPMTag_PRETRANSPROG      => 1153,
     RPMTag_POSTTRANSPROG     => 1154,
     RPMTag_DISTTag         => 1155,
     RPMTag_SUGGESTSName      => 1156,
     RPMTag_SUGGESTSVersion    => 1157,
     RPMTag_SUGGESTSFlags     => 1158,
     RPMTag_ENHANCESName      => 1159,
     RPMTag_ENHANCESVersion    => 1160,
     RPMTag_ENHANCESFlags     => 1161,
     RPMTag_PRIORITY        => 1162,
     RPMTag_CVSID         => 1163,
     RPMTag_BLINKPKGID       => 1164,
     RPMTag_BLINKHDRID       => 1165,
     RPMTag_BLINKNEVRA       => 1166,
     RPMTag_FLINKPKGID       => 1167,
     RPMTag_FLINKHDRID       => 1168,
     RPMTag_FLINKNEVRA       => 1169,
     RPMTag_PACKAGEORIGIN     => 1170,
     RPMTag_TRIGGERPREIN      => 1171,
     RPMTag_BUILDSUGGESTS     => 1172,
     RPMTag_BUILDENHANCES     => 1173,
     RPMTag_SCRIPTSTATES      => 1174,
     RPMTag_SCRIPTMETRICS     => 1175,
     RPMTag_BUILDCPUCLOCK     => 1176,
     RPMTag_FILEDIGESTALGOS    => 1177,
     RPMTag_VARIANTS        => 1178,
     RPMTag_XMAJOR         => 1179,
     RPMTag_XMINOR         => 1180,
     RPMTag_REPOTag         => 1181,
     RPMTag_KEYWORDS        => 1182,
     RPMTag_BUILDPLATFORMS     => 1183,
     RPMTag_PACKAGECOLOR      => 1184,
     RPMTag_PACKAGEPREFCOLOR   => 1185,
     RPMTag_XATTRSDICT       => 1186,
     RPMTag_FILEXATTRSX      => 1187,
     RPMTag_DEPATTRSDICT      => 1188,
     RPMTag_CONFLICTATTRSX     => 1189,
     RPMTag_OBSOLETEATTRSX     => 1190,
     RPMTag_PROVIDEATTRSX     => 1191,
     RPMTag_REQUIREATTRSX     => 1192,
     RPMTag_BUILDProvides     => 1193,
     RPMTag_BUILDOBSOLETES     => 1194,
     RPMTag_DBINSTANCE       => 1195,
     RPMTag_NVRA          => 1196,
     RPMTag_FILENameS       => 5000,
     RPMTag_FILEPROVIDE      => 5001,
     RPMTag_FILEREQUIRE      => 5002,
     RPMTag_FSNameS         => 5003,
     RPMTag_FSSIZES         => 5004,
     RPMTag_TRIGGERCONDS      => 5005,
     RPMTag_TRIGGERTYPE      => 5006,
     RPMTag_ORIGFILENameS     => 5007,
     RPMTag_LONGFilesIZES     => 5008,
     RPMTag_LONGSIZE        => 5009,
     RPMTag_FILECAPS        => 5010,
     RPMTag_FILEDIGESTALGO     => 5011,
     RPMTag_BUGURL         => 5012,
     RPMTag_EVR           => 5013,
     RPMTag_NVR           => 5014,
     RPMTag_NEVR          => 5015,
     RPMTag_NEVRA         => 5016,
     RPMTag_HeaderCOLOR      => 5017,
     RPMTag_VERBOSE         => 5018,
     RPMTag_EpochNUM        => 5019,
     RPMTag_PREINFlags       => 5020,
     RPMTag_POSTINFlags      => 5021,
     RPMTag_PREUNFlags       => 5022,
     RPMTag_POSTUNFlags      => 5023,
     RPMTag_PRETRANSFlags     => 5024,
     RPMTag_POSTTRANSFlags     => 5025,
     RPMTag_VERIFYSCRIPTFlags   => 5026,
     RPMTag_TRIGGERSCRIPTFlags   => 5027,
     RPMTag_COLLECTIONS      => 5029,
     RPMTag_POLICYNameS      => 5030,
     RPMTag_POLICYTYPES      => 5031,
     RPMTag_POLICYTYPESIndexES   => 5032,
     RPMTag_POLICYFlags      => 5033,
     RPMTag_VCS           => 5034,
     RPMTag_ORDERName       => 5035,
     RPMTag_ORDERVersion      => 5036,
     RPMTag_ORDERFlags       => 5037,
     RPMTag_MSSFMANIFEST      => 5038,
     RPMTag_MSSFDOMAIN       => 5039,
     RPMTag_INSTFILENameS     => 5040,
     RPMTag_REQUIRENEVRS      => 5041,
     RPMTag_PROVIDENEVRS      => 5042,
     RPMTag_OBSOLETENEVRS     => 5043,
     RPMTag_CONFLICTNEVRS     => 5044,
     RPMTag_FILENLINKS       => 5045
     );
   for Tags_Type'Size use 32;

   type Format_Type is
     (RPM_NULL_TYPE,
     RPM_CHAR_TYPE,
     RPM_int8_TYPE,
     RPM_int16_TYPE,
     RPM_int32_TYPE,
     RPM_int64_TYPE,
     RPM_STRING_TYPE,
     RPM_BIN_TYPE,
     RPM_STRING_ARRAY_TYPE,
     RPM_I18NSTRING_TYPE);
   for Format_Type use
     (RPM_NULL_TYPE => 0,
     RPM_CHAR_TYPE => 1,
     RPM_int8_TYPE => 2,
     RPM_int16_TYPE => 3,
     RPM_int32_TYPE => 4,
     RPM_int64_TYPE => 5,
     RPM_STRING_TYPE => 6,
     RPM_BIN_TYPE => 7,
     RPM_STRING_ARRAY_TYPE => 8,
     RPM_I18NSTRING_TYPE => 9
     );
   for Format_Type'Size use 32;
end ARPM_RPM_Types;
